apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: harshalvk/farm-gateway:v1
          ports:
            - containerPort: 8000
          env:
            - name: FERTILIZER_URL
              value: "http://fertilizer-svc:8000"
            - name: CROP_URL
              value: "http://crop-svc:8000"
            - name: PLANT_URL
              value: "http://plant-diseas-svc:8000"
            - name: SOIL_URL
              value: "http://soil-health-svc:8000"
            - name: MONGO_URL # ← replace the old hardcoded value
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  selector:
    app: gateway
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
