apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-disease
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plant-disease
  template:
    metadata:
      labels:
        app: plant-disease
    spec:
      containers:
        - name: fertilizer
          image: harshalvk/plant-diseas-model:v2
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: plant-disease-svc
spec:
  selector:
    app: plant-disease
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
